# ONE DIMENSIONAL ARRAY

In [47]:
import numpy as np

my_list = [2,5,4,7]
print("The list formed is: ", my_list)

arr = np.array(my_list)
print("The array formed from list is: ", arr)
print("Element in index of arr 2 is :", arr[2])
print("Datatype of arr is :", type(arr))
print("Dimension of arr is: ", arr.shape)



The list formed is:  [2, 5, 4, 7]
The array formed from list is:  [2 5 4 7]
Element in index of arr 2 is : 4
Datatype of arr is : <class 'numpy.ndarray'>
Dimension of arr is:  (4,)


# TWO DIMENSIONAL ARRAY

In [48]:
list_1=[4,5,6,3]
list_2=[2,5,5,3]
list_3=[9,5,6,6]
list_4=[99,9,6,8]

new_arr = np.array([list_1,list_2,list_3,list_4])
print("The new array formed from 4 list is: \n", new_arr)
print("Selecting all rows and all columns of new_arr gives : \n",new_arr[:,:])
print("Selecting first two rows and all columns of new_arr gives : \n",new_arr[0:2,:])
print("Selecting last two rows and last two columns of new_arr gives : \n",new_arr[2:,2:])
print("Selecting last three rows and last one columns of new_arr gives : \n",new_arr[1:,3:])
print("Datatype of new_arr is :", type(new_arr))
print("Dimension of new_arr is: ", new_arr.shape)
print('\n')
print("Reshape the new array as 1 row and 16 columns : \n", new_arr.reshape(1,16))
print('\n')
print("Reshape the new array as 2 row and 8 columns : \n", new_arr.reshape(2,8))


The new array formed from 4 list is: 
 [[ 4  5  6  3]
 [ 2  5  5  3]
 [ 9  5  6  6]
 [99  9  6  8]]
Selecting all rows and all columns of new_arr gives : 
 [[ 4  5  6  3]
 [ 2  5  5  3]
 [ 9  5  6  6]
 [99  9  6  8]]
Selecting first two rows and all columns of new_arr gives : 
 [[4 5 6 3]
 [2 5 5 3]]
Selecting last two rows and last two columns of new_arr gives : 
 [[6 6]
 [6 8]]
Selecting last three rows and last one columns of new_arr gives : 
 [[3]
 [6]
 [8]]
Datatype of new_arr is : <class 'numpy.ndarray'>
Dimension of new_arr is:  (4, 4)


Reshape the new array as 1 row and 16 columns : 
 [[ 4  5  6  3  2  5  5  3  9  5  6  6 99  9  6  8]]


Reshape the new array as 2 row and 8 columns : 
 [[ 4  5  6  3  2  5  5  3]
 [ 9  5  6  6 99  9  6  8]]


# Copy function and Broadcasting

In [77]:
array_4 = np.array([2,4,5,9,0,8,6])

array_5 = array_4.copy()
#copy is used to store array_5 in another memory space so that array_4 is not altered due to changes in array_5
array_5[2:]=1000
print("Using copy function in the array :", array_4)
print("And replacement of certain elements the array becomes :", array_5)


Using copy function in the array : [2 4 5 9 0 8 6]
And replacement of certain elements the array becomes : [   2    4 1000 1000 1000 1000 1000]


# MAKING ARRAY USING OTHERS KEYWORDS

In [82]:

#To make array from series of elements using keyword :

#arange
array_1 = np.arange(0,10)
print("Array of first 10 numbers : ",array_1)

array_2 = np.arange(0,10,step=2)
print("Array of numbers with a diff of 2: ",array_2)

#linspace
array_3 = np.linspace(0,10,50)
print("Array from 0 to 10 with 50 numbers in between : \n",array_3)

print('\n')
array_a = np.ones(5)
print("Array having 5 float ones in it : ", array_a)

array_b = np.ones((5), dtype=int)
print("Array having 5 integer ones in it : ", array_b)

array_c = np.ones((2,5), dtype=int)
print("Two dimensional 2*5 array having integer ones in it : \n", array_c)

array_d = np.ones((2,5))
print("Two dimensional 2*5 array having float ones in it : \n", array_d)

array_e = np.random.rand(3,3)
print("Two dimensional 3*3 array having random numbers in uniform distribution : \n", array_e)

array_f = np.random.randn(3,3)
print("Two dimensional 3*3 array having random numbers in standard normal distribution : \n", array_f)

array_g = np.random.randint(0,100,8)
print("One dimensional array having 8 random numbers in range 0 to 100 : \n", array_g)

array_h = np.random.randint(0,100,8).reshape(2,4)
print("Two dimensional array having 8 random numbers in range 0 to 100 : \n", array_h)

array_i = np.random.random_sample((1,5))
print("One dimensional array having 5 random numbers in range 0 to 1 : \n", array_i)

array_i = np.random.random_sample((2,5))
print("Two dimensional array having 5 random numbers in each row, in range 0 to 1 : \n", array_i)

Array of first 10 numbers :  [0 1 2 3 4 5 6 7 8 9]
Array of numbers with a diff of 2:  [0 2 4 6 8]
Array from 0 to 10 with 50 numbers in between : 
 [ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


Array having 5 float ones in it :  [1. 1. 1. 1. 1.]
Array having 5 integer ones in it :  [1 1 1 1 1]
Two dimensional 2*5 array having integer ones in it : 
 [[1 1 1 1 1]
 [1 1 1 1 1]]
Two dimensional 2*5 array having float ones in it : 
 [

# APPLYING ARITHEMATIC OPERATIONS ON ARRAY

In [61]:
array_6 = np.array([2,5,3,8,10])
print("when all elements of array_6 are added with 4 ", array_6+4)
print("when all elements of array_6 are subtracted from 4 ", array_6-4)
print("when all elements of array_6 are multiplied with 4 ", array_6*4)
print("when all elements of array_6 are divided with 4 ", array_6/4)

print('\n')

array_7 = np.array([20,8,3,1,9])
print("when all elements of array_6 are added with elements of array_7 ", array_6 + array_7)
print("when all elements of array_6 are subtracted from elements of array_7 ", array_6 - array_7)
print("when all elements of array_6 are multiplied with elements of array_7 ", array_6 * array_7)
print("when all elements of array_6 are divided with elements of array_7 ", array_6 / array_7)

when all elements of array_6 are added with 4  [ 6  9  7 12 14]
when all elements of array_6 are subtracted from 4  [-2  1 -1  4  6]
when all elements of array_6 are multiplied with 4  [ 8 20 12 32 40]
when all elements of array_6 are divided with 4  [0.5  1.25 0.75 2.   2.5 ]


when all elements of array_6 are added with elements of array_7  [22 13  6  9 19]
when all elements of array_6 are subtracted from elements of array_7  [-18  -3   0   7   1]
when all elements of array_6 are multiplied with elements of array_7  [40 40  9  8 90]
when all elements of array_6 are divided with elements of array_7  [0.1        0.625      1.         8.         1.11111111]


# APPLYING LOGICAL OPERATIONS ON AN ARRAY

In [64]:
print("Checking whether elements of array_6 is less than 3 or not  ", array_6<3)
print("Checking whether elements of array_6 is greater than 3 or not  ", array_6>3)
print("Checking whether elements of array_6 is less than array_7 elements or not  ", array_6<array_7)
print("Checking whether elements of array_6 is greater than array_7 elements or not  ", array_6>array_7)


Checking whether elements of array_6 is less than 3 or not   [ True False False False False]
Checking whether elements of array_6 is greater than 3 or not   [False  True False  True  True]
Checking whether elements of array_6 is less than array_7 elements or not   [ True  True False False False]
Checking whether elements of array_6 is greater than array_7 elements or not   [False False False  True  True]
