<a href="https://colab.research.google.com/github/RemyaRS/Python-Basics/blob/main/Test_Basic_Program.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Map Two Lists into a Dictionary
2. Calculate BMI
3. Pattern printing
4. Find longest Word From Sentence or Text Sorting Dictionary by Value
5. Python matrix
6. Move all Zeros present in an Array/List to the End
7. Check If Two Strings are Anagram

In [ ]:
# 1. Map Two Lists into a Dictionary
L1=['sagdh','jdsk','sdda','shdysf']
L2=[34,18,19,23]
D1=dict(zip(L1,L2))
D2=dict(zip(L2,L1))
print(D1)
print('')
print(D2)

{'sagdh': 34, 'jdsk': 18, 'sdda': 19, 'shdysf': 23}

{34: 'sagdh', 18: 'jdsk', 19: 'sdda', 23: 'shdysf'}


In [ ]:
# 2. Calculate BMI
weight =float(input("Enter the weight in Kg:"))
height =float(input("Enter the height in cm:"))
bmi=(weight**100)/(height**2)
bmi
if(bmi<16):
  print("Severely Underweight")
elif(16>=bmi and bmi<18.5):
  print("Underweight")
elif(18.5>=bmi and bmi<25):
  print("Healthy")
elif(25>=bmi and bmi<30):
  print("Overweight")
elif(bmi>=30):
  print("Severely Overweight")

Enter the weight in Kg:63
Enter the height in cm:156
Severely Overweight


In [ ]:
# 3. Pattern printing

#Right Triangles
def pypart(n):
  for i in range(0,n):
    for j in range(0,i+1):
      print("* ", end="")
    print("\r")
n = 5
pypart(n)

* 
* * 
* * * 
* * * * 
* * * * * 


In [ ]:
def pypart(n):
  k=2*n-2
  for i in range(0,n):
    for j in range(0,k):
      print(end=" ")
    k=k-2
    for j in range(0,i+1):
      print("* ", end="")
    print("\r")
    
# Driver Code
n = 5
pypart(n)

        * 
      * * 
    * * * 
  * * * * 
* * * * * 


In [ ]:
def triangle(n):
  k=n-1
  for i in range(0,n):
    for j in range(0,k):
      print(end=" ")
    k=k-1
    for j in range(0,i+1):
      print("* ", end="")
    print("\r")
    
# Driver Code
n = 5
triangle(n)

    * 
   * * 
  * * * 
 * * * * 
* * * * * 


In [ ]:
# 4. Find longest Word From Sentence or Text Sorting Dictionary by Value

l1=input("Enter the sentence :")
longest=max(l1.split(), key=len)
print("The longest word in the sentence is:", longest)

Enter the sentence :safas asdasmd dasklas
The longest word in the sentence is: asdasmd


In [ ]:
# 5. Python matrix

import numpy as np

x=np.array([[1,2],[4,5]])
y=np.array([[1,2],[4,5]])
print("x :")
print(x)
print(" ")
print("y :")
print(y)
print(" ")
print("x+y :")
print(np.add(x,y))
print(" ")
print("sum of elements matrix x")
print(np.sum(x))
print(" ")
print("sum of elements of rows matrix x")
print(np.sum(x,axis=0))
print(" ")
print("sum of elements of coloumn matrix x")
print(np.sum(x,axis=1))
print(" ")
print("x-y :")
print(np.subtract(x,y))
print(" ")
print("x*y :")
print(np.multiply(x,y))
print(" ")
print("x/y :")
print(np.divide(x,y))
print(" ")
print("dot product :")
print(np.dot(x,y))
print(" ")
print("square root :")
print(np.sqrt(x))
print(" ")
print("Transpose :")
print(x.T)
print(" ")

x :
[[1 2]
 [4 5]]
 
y :
[[1 2]
 [4 5]]
 
x+y :
[[ 2  4]
 [ 8 10]]
 
sum of elements matrix x
12
 
sum of elements of rows matrix x
[5 7]
 
sum of elements of coloumn matrix x
[3 9]
 
x-y :
[[0 0]
 [0 0]]
 
x*y :
[[ 1  4]
 [16 25]]
 
x/y :
[[1. 1.]
 [1. 1.]]
 
dot product :
[[ 9 12]
 [24 33]]
 
square root :
[[1.         1.41421356]
 [2.         2.23606798]]
 
Transpose :
[[1 4]
 [2 5]]
 


In [ ]:
# 6. Move all Zeros present in an Array/List to the End

# Method 1
import numpy as np
a=[1,0,7,3,0,4,5,2,0,7]
n=len(a)
b=np.zeros(n, dtype=int)
j=0


for i in range(n):
  if a[i]!=0:
    b[j]=a[i]
    j=j+1
print(b)

[1 7 3 4 5 2 7 0 0 0]


In [ ]:
# 7. Check If Two Strings are Anagram
# An anagram is a word or phrase formed by rearranging the letters of a different word or phrase, typically using all the original letters exactly once.
#For example --- : adobe ----> abode.
str1=input("Enter first string")
str2=input("Enter second string")
str1_sort=sorted(str1)
str2_sort=sorted(str2)
if (len(str1)==len(str2)):
  if (str1_sort==str2_sort):
    print("Two strings are anagram")
  else:
    print("Two strings are not anagram")
else:
  print("Two strings are not anagram") 


Enter first stringtyr
Enter second stringtry
Two strings are anagram
